import {
  animals,
  sports,
  body,
  jobs,
  countries,
  home,
  fruits,
  transport,
} from '@/assets/image';

export const topics = [
  {
    id: 1,
    name: 'animals',
    img: animals,
    words: [
      'lizard',
      'raven',
      'crocodile',
      'kangaroo',
      'snake',
      'dragon',
      'shark',
      'worm',
      'mouse',
      'mosquito',
      'eagle',
      'whale',
      'dolphin',
      'buffalo',
      'sheep',
      'cockroah',
      'fly',
      'dragon',
      'otter',
      'sealion',
      'butterfly',
      'dinosaur',
      'hippo',
      'giraffe',
      'penguin',
      'wolf',
      'goat',
      'gorilla',
      'horse',
      'rhino',
      'cheetah',
      'elephant',
      'zebra',
    ],
  },
  {
    id: 2,
    name: 'sports',
    img: sports,
    words: [
      'soccer',
      'badminton',
      'football',
      'swiming',
      'athletics',
      'tennis',
      'basketball',
      'hockey',
      'golf',
      'chess',
      'skateboarding',
      'voleyball',
      'cycling',
      'rowing',
      'diving',
      'archery',
      'judo',
      'gymnastics',
      'baseball',
      'ice skating',
      'boxing',
      'karate',
      'fencing',
      'handball',
      'bowling',
      'billards',
    ],
  },
  {
    id: 3,
    name: 'body',
    img: body,
    words: [
      'teeth',
      'tongue',
      'leg',
      'foot',
      'finger',
      'hand',
      'head',
      'hair',
      'neck',
      'ear',
      'nose',
      'eyes',
      'mouth',
      'knee',
      'nail',
      'chest',
      'shoulder',
      'elbow',
      'heel',
      'back',
      'forehead',
      'waist',
      'thigh',
      'ankle',
      'armpit',
      'cheek',
      'toe',
      'chin',
      'eyebrow',
      'stomach',
    ],
  },
  {
    id: 4,
    name: 'jobs',
    img: jobs,
    words: [
      'policeman',
      'scientist',
      'receptionist',
      'firefighter',
      'security',
      'caster',
      'journalist',
      'photographer',
      'cameraman',
      'pianist',
      'chef',
      'mechanic',
      'cashier',
      'hairdresser',
      'actress',
      'businessman',
      'pilot',
      'astronaut',
      'nanny',
      'accountant',
      'athlete',
      'computer technician',
      'dancer',
      'waiter',
      'actress',
    ],
  },
  {
    id: 5,
    name: 'countries',
    img: countries,
    words: [
      'Vietnam',
      'Korea',
      'Argentina',
      'Thailand',
      'France',
      'England',
      'China',
      'Portugal',
      'Spain',
      'Cambodia',
      'Singapore',
      'Turkey',
      'Australia',
      'Japan',
      'Switzerland',
      'Germany',
      'Egypt',
      'Greek',
      'Poland',
      'Cameroon',
      'Finland',
      'Netherland',
      'Ukraina',
      'Russia',
      'Sweden',
      'Ghana',
      'South Africa',
    ],
  },
  {
    id: 6,
    name: 'home',
    img: home,
    words: [
      'bed',
      'sofa',
      'door',
      'chair',
      'table',
      'desk',
      'window',
      'roof',
      'clock',
      'air condition',
      'computer',
      'tivi',
      'bowl',
      'towel',
      'lock',
      'mirror',
      'bin',
      'shelf',
      'stove',
      'cushion',
      'cupboard',
      'fridge',
      'spoon',
      'knife',
      'vase',
      'dish',
      'toilet',
      'kettle',
      'shower',
      'sink',
      'washing machine',
      'vacuum cleaner',
    ],
  },
  {
    id: 7,
    name: 'fruits',
    img: fruits,
    words: [
      'watermelon',
      'apple',
      'pineapple',
      'strawberry',
      'grape',
      'dragon fruit',
      'durian',
      'mangosteen',
      'banana',
      'lemon',
      'orange',
      'coconut',
      'mango',
      'peach',
      'pear',
      'papaya',
      'cherry',
      'avocado',
      'star fruit',
    ],
  },
  {
    id: 8,
    name: 'transport',
    img: transport,
    words: [
      'bus',
      'motorbike',
      'ambulance',
      'rocket',
      'helicopter',
      'plane',
      'boat',
      'bicycle',
      'train',
      'submarine',
      'aircraft',
      'hot air balloon',
      'truck',
      'scooter',
      'escalator',
      'elevator',
      'limo',
      'yacht',
      'cyclo',
      'car',
      'roadster',
      'fire engine',
      // 'a b c',
      // 'abcd',
      // 'abcde',
    ],
  },
];

export default topics;
